const ACTION_TYPES = {
  GET_NEWS : "GET_NEWS",
  CLEAR_GET_NEWS : "CLEAR_GET_NEWS",

  GET_PROJECT_NAME_RES : "GET_PROJECT_NAME_RES",
  CLEAR_PROJECT_NAME_RES : "CLEAR_PROJECT_NAME_RES"
};

export default ACTION_TYPES;
